Criação de Cards
juliadelisposte/quasar-blog pull request #1
Opened 2021-04-20 21:05 UTC by juliadelisposte

2021-04-20 21:44 UTC, felipejuzo02 requested changes

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      <div class='text-h6'>{{title}}</div>
Adicionar espaçamento dentro das chaves. Ex: `{{ title }}`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +  <div class="last-alteration"> Data da última alteração: {{alteration}} </div>
Adicionar espaçamento dentro das chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      <div>Autor: {{author}}</div>
Adicionar espaçamento dentro das chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +       <div>Data: {{date}} </div>
Adicionar espaçamento dentro das chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +       <div>Categoria: {{category}}</div>
Adicionar espaçamento dentro das chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      <span class="page-post__description">{{description}}</span>
Adicionar espaçamento dentro das chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      type: String
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    alteration: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    button: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    button_two: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    button_three: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    description: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    photo: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    author: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    date: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    category: {
além do tipo, também passar o valor `default`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +.page-post{
adicionar espaço antes da chave. Ex: `.page-post {`

2021-04-20 21:44 UTC, felipejuzo02 commented on src/pages/Index.vue
> +   .text-h6{
adicionar espaço antes da abertura de chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/pages/Index.vue
> +  .title{
adicionar espaço antes da abertura de chaves

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/Card.vue
> +<!-- <div class ="row"> -->
remover classe comentada

2021-04-20 21:44 UTC, felipejuzo02 commented on src/components/Card.vue
> +            </div>
ajustar identação ao fechar a div

2021-04-20 21:48 UTC, eliasassuncao requested changes

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +<!-- <div class ="row"> -->
remover div comentada

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +<div class="page-post">
identação incorreta

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +<template v-slot: card>
todo componente, page, deve conter um `<template> conteúdo html... </template>` , onde ele não é um `v-slot`

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +  <div class="shadow-12">
a idéia de ter um componente Card, seria que ele fosse o mais genérico possível. A partir dele, poderia criar um componente de card especifico, um exemplo:


Componente de card:
```
<div class="card">
  <slot /> <---- conteúdo do card
</div>

.card { border-radius: 12px; ... } <---- estilo do card, para padronizar o card utilizado no projeto.
```

Componente CardPost:

```
<card> <----- utilizando a estrutura padronizada pra quando eu for criar um card
 <div>Autores: {{ authorName}}</div> <----------  conteúdo do meu card, e estilo, especifico pra quando for um card de post
<card>

```

Pagína de Post

```
<card-post author-name="Cleyton" /> <---- passando a propriedade
```

Detalhe, se fosse muitos atributos além do author-name, poderia passar somente um objeto `content`, pra não ter muitas props

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +          <card-post title="title" author="desconhecido" date="20/04/2021" category="categoria" photo="https://besthqwallpapers.com/Uploads/27-12-2017/35250/thumb2-4k-living-room-white-and-gray-inter
muitas propriedades, poderia ter somente um content em um objeto, pra não poluir a view e não precisar criar N props.

exemplo:

```
<card-post  content="contentCard"/>

contentCard: {
  title: 'cleyton',
   author: 'desconhecido',
  ....
}

```

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +            </div>
identação incorreta

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +import CardPost from './CardPost.vue'
quebra de linha

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +  components: { CardPost },
quebra de linha

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +  props: {
ter somente uma props `content`, igual comentado acima

2021-04-20 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +<style>
estilo não usado, pode remover

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/components/Card.vue
> +  props: {
Criar um único objeto para ser utilizado e a ao passar ele para dentro do componente passar esse objeto com todas essas informações que você precisa utilizar, na utilização dele você já utilizaria objeto.propriedade (objeto.title).

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +      <div class='text-h6'>{{title}}</div>
neste caso usou o text-h6 com qual intenção?

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +      <q-img :src="`${photo}`" style="width: 100%" native-context-menu>
não usar style-line

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +      <q-btn
Organização dos elementos tipo q-btn pode ser na horizontal, quebrar somente se exceder muito, o vs code tem inclusive uma linha vertical para auxiliar no quanto passou, se passou da segunda linha é melhor quebrar para outra, fora isso pode manter.

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +      sizes: ['sm'],
o sizes e icons contém somente um elemento? serão adicionados mais algum? caso não você pode utilizar algo mais direto como uma string.

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/layouts/MainLayout.vue
> +          @click="leftDrawerOpen = !leftDrawerOpen">
regra no código, utilizar regra dentro de uma computada ou método... o que ela faz neste caso?

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/layouts/MainLayout.vue
> +          <q-list style="min-width: 100px">
não utilizar style-line, ou evitar rs 100% 👯

2021-04-20 22:56 UTC, cassioalmeida2 commented on src/pages/Index.vue
> +   .text-h6{
não precisa criar um text-h6, o quasar já tem o h6 e você pode utilizá-lo como text-h6, caso precisa alterar o valor do h6 pode fazer isso diretamente no variables do quasar.

2021-04-22 14:26 UTC, eliasassuncao requested changes

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +<div>
idetanção da forma errada

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +  <div class="last-alteration"> Data da última alteração: {{alteration}} </div>
classe não existente, e não está no padrão BEM

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      <q-img :src="`${photo}`" style="width: 100%" native-context-menu>
nãao precisa colocar em template string, somente `:src="photo"` já funciona

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +    <div class="page-post__image">
a classe deveria ser  `card-post__image`, `page` somente para páginas

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +    <div class="page-post__action">
a classe deveria ser card-post__action, page somente para páginas

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/Card.vue
> +<div class="page-post">
a classe deveria ser somente `card`, page somente para páginas, e é um card, não um post

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/Card.vue
> +    <div class="page-post__card">
a classe deveria ser `somente `card`, page somente para páginas, e é um card, não um post

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/Card.vue
> +      <div class="page-post__header--size-lg">
a classe deveria ser somente `card__header`, page somente para páginas, e é um card, não um post.

`--valor` são pra modificadores, nesse caso não precisaria. Exemplo:


```
.button {
  background-color: orange;
  color: #fff;
  font-size: 15px;
  
 &--red {
    background-color: red;
 }
}

<button class="button button--red" /> <--- vai ser mantido todas as propriedades, modificando somente a cor do botão

```

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/Card.vue
> +        <div class="page-post__title">
a classe deveria ser somente `card__title`, page somente para páginas, e é um card, não um post

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +        v-for="size in sizes" :key="`btn_size_rd_${size}`"
pq está utilizando um for?

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +        :label="`${button}`"
não precisa de template string, `:label="button"` já funciona

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      </div>
identação de forma errada

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      sizes: ['sm'],
vc está loopando esses sizes pra criar os botões, se é somente um item necessita de v-for?

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      icons: ['navigation']
esse icons está sendo utilizado?

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/CardPost.vue
> +     width: 20%;
valor muito especifico, o q isso está fazendo?

2021-04-22 14:26 UTC, eliasassuncao commented on src/components/EssentialLink.vue
>        default: '#'
precisa do `#`  ?

2021-04-22 14:26 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +                <EssentialLink v-for="link in essentialLinks" :key="link.title" v-bind="link"/>
componentes devem ser chamados em snake-case, `<essential-link/>`

2021-04-22 14:26 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +    title: 'Home',
se existe somente um item, precisa estar dentro de um array?

2021-04-22 14:26 UTC, eliasassuncao commented on src/pages/Index.vue
> +    margin-left: 80px;
é bom padronizar os valores dos margins e paddings utilizados, portanto utilizar as classes do quasar.

https://quasar.dev/style/spacing

2021-04-22 14:26 UTC, eliasassuncao commented on src/pages/Index.vue
> +    margin-left: 30px;
é bom padronizar os valores dos margins e paddings utilizados, portanto utilizar as classes do quasar.

https://quasar.dev/style/spacing

2021-04-22 14:26 UTC, eliasassuncao commented on src/router/routes.js
> +    component: () => import('components/Card.vue')
deveria ser uma página, não um componente

2021-04-23 14:43 UTC, juliadelisposte commented on src/components/CardPost.vue
> +      <div class='text-h6'>{{title}}</div>
A intenção foi deixar o título maior e não precisar utilizar o scss para isso

2021-04-23 14:59 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +          @click="leftDrawerOpen = !leftDrawerOpen">
Nesta parte eu só apaguei alguns códigos que eu não iria utilizar, mas isto já estava dentro do projeto que é a parte do menu que fica em cima de tudo, eu não havia notado que neste caso ela não tinha funcionalidade nenhuma, eu já apaguei.

2021-04-23 15:04 UTC, juliadelisposte commented on src/pages/Index.vue
> +   .text-h6{
Neste caso eu utilizei o text-h6 para conseguir centralizar o texto no meio da página, eu tentei com os espaçamentos do quasar deixar centralizado, mas nenhum ficou no meio:
.text-h6{
  margin-left: 150px;
}
eu só alterei a posição dele

2021-04-26 15:15 UTC, eliasassuncao requested changes

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/Card.vue
> +    width: 30%;
width muito especifico, pra o que seria? vc poderia utilizar `col` no lado de fora onde vc chama o card

https://quasar.dev/layout/grid/row#introduction
```
<div class="col-12"> <-- controla o tamanho pela div, e não no componente, pra não engessar o componente.
 <card/>
</div>
```

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/CardPost.vue
> +  <card content='contentCard'>
componente card não espera uma props chamada `content`, portanto remover props

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/CardPost.vue
> +        <q-btn size="12px" color="primary" text-color="white" :label="`${content.button}`" />
não é necessária o `${}`, somente `:label="content.button"`  já funciona, qd vc quer passar um valor js

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      title: {
não precisa listar todas as props q vão estar no content, pq dessa forma continuaria o problema de se ter uma chave a mais, teria q criar mais uma props. Somente dizendo q o content já resolve

```
content: {
 type: Object,
  default: () => ({}) 
}

```

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      button_two: {
essas propriedades vão ser removidas, mas só pra lembrar, utilizar o padrão camelCase, e faltou  setar qual o valor default da props.

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/CardPost.vue
> +  q-img{
classe fora do padrão BEM, e pra o `width: 100%` existe a classe `full-width` do quasar

2021-04-26 15:15 UTC, eliasassuncao commented on src/components/EssentialLink.vue
>        default: '#'
`#` ainda permanece, é necessário?

2021-04-26 15:15 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +                <essential-link v-for="link in essentialLinks" :key="link.title" v-bind="link"/>
o que o v-bind está fazendo? é necessário?

2021-04-26 15:15 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +  link: '/'
somente `link: ''` vazio já não funciona?

2021-04-26 15:15 UTC, eliasassuncao commented on src/pages/Index.vue
> +  },
faltou espaçamento

2021-04-26 17:07 UTC, juliadelisposte commented on src/components/Card.vue
> +    width: 30%;
O Width eu coloquei para declarar só a largura mesmo do card, mas já troquei pelo **col**

2021-04-26 17:13 UTC, juliadelisposte commented on src/components/CardPost.vue
> +  <card content='contentCard'>
removido

2021-04-26 17:15 UTC, juliadelisposte commented on src/components/CardPost.vue
> +        <q-btn size="12px" color="primary" text-color="white" :label="`${content.button}`" />
feito

2021-04-26 17:29 UTC, juliadelisposte commented on src/components/CardPost.vue
> +      title: {
feito

2021-04-26 17:30 UTC, juliadelisposte commented on src/components/CardPost.vue
> +      button_two: {
propriedades removidas

2021-04-26 17:35 UTC, juliadelisposte commented on src/components/CardPost.vue
> +  q-img{
Fazendo esta mudança eu notei que não era necessário declarar o tamanho, já foi retirado

2021-04-26 18:22 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +  link: '/'
funcionou sim, já retirei

2021-04-26 18:54 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +                <essential-link v-for="link in essentialLinks" :key="link.title" v-bind="link"/>
eu peguei essa estrutura pronta do projeto já, eu fiz alguns testes aqui e se eu retirar ele o nome do menu fica vazio
(com o v-bind)
![image](https://user-images.githubusercontent.com/36795911/116135510-9ab16b80-a6a7-11eb-9a66-7f0689341d44.png)

(sem o v-bind)
![image](https://user-images.githubusercontent.com/36795911/116135606-b288ef80-a6a7-11eb-892c-39bb2641252a.png)

2021-04-26 19:33 UTC, cassioalmeida2 commented on src/components/Card.vue
> +  <div class="card">
utilizar classe card no padrão BEM

2021-04-26 19:33 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +  <card contentCard>
esse contentCard em camelcase está funcionando? seria uma props booleana? o correto ao chamar uma props fora do componente é com o hífen... Ex: contentCard ficaria content-card, se ela recebesse um valor ficaria content-card="valor".

2021-04-26 19:33 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +        <div class='text-h6'> {{ content.title }} </div>
aqui não precisa deixar o espaço das tags, somente dentro das expressions ({{}}).

2021-04-26 19:33 UTC, cassioalmeida2 commented on src/layouts/MainLayout.vue
> +    title: 'Home',
caso seja um item pode criar um único objeto ao invés de um array.

2021-04-26 19:33 UTC, cassioalmeida2 commented on src/pages/Index.vue
> +    cardContent () {
agora sim :D

2021-04-26 19:35 UTC, felipejuzo02 approved these changes

2021-04-26 19:45 UTC, juliadelisposte commented on src/components/CardPost.vue
> +  <card contentCard>
Na verdade o contentCard está errado, eu acabei me confundindo com a computada, já exclui ele

2021-04-26 19:53 UTC, eliasassuncao commented on src/components/Card.vue
> +  <div class="card">
está certo Cassinho, quando é componente é somente o nome do componente

2021-04-26 19:57 UTC, juliadelisposte commented on src/components/Card.vue
> +  <div class="card">
Alinhamos sobre esse caso e por ser um componente ele já está no padrão BEM

2021-04-26 20:03 UTC, eliasassuncao requested changes

2021-04-26 20:03 UTC, eliasassuncao commented on src/components/CardPost.vue
> +        <q-btn size="12px" color="primary" text-color="white" :label="content.button_three" />
utilizar camelCase, `:label="content.buttonTwo"`, `:label="content.buttonThree"`, etc

2021-04-26 20:03 UTC, eliasassuncao commented on src/components/CardPost.vue
> +
não deve conter espaçamento entre o import e o script

2021-04-26 20:03 UTC, eliasassuncao commented on src/components/CardPost.vue
> +  props: {
quebra de linha:

```
  components: {
    Card
  },

  props: {
 ...
```

2021-04-26 20:03 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +                <essential-link v-for="link in essentialLinks" :key="link.title" v-bind="link"/>
vc tirando o `v-bind`, e passando a props title e link q o componente tem não funciona?

2021-04-26 20:03 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +
entre script e import não tem espaçamento

2021-04-26 20:03 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +    link: ''
Home e Posts vai pro mesmo link?

2021-04-26 20:09 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +    link: ''
Ainda não há a página de posts, por isso acabei deixando vazio o link do Post

2021-04-26 21:48 UTC, eliasassuncao approved these changes

2021-04-26 21:48 UTC, eliasassuncao commented on src/components/Card.vue
> +<div class="col-12">
não seria melhor essa div ficar do lado de fora? se eu quiser usar um card, e q ele ocupe `col-3` não iria ter como

2021-04-26 21:48 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      <div>Autor: {{content.author}} </div>
falta espaçamento entre as chaves

2021-04-28 15:11 UTC, cassioalmeida2 approved these changes

2021-04-29 13:06 UTC, merged