Author Creation
juliadelisposte/quasar-blog pull request #3
Opened 2021-05-17 17:34 UTC by juliadelisposte

2021-05-17 17:38 UTC, felipejuzo02 commented on src/pages/authors/authorsCreate.vue
> +  <div class="authors-create">
e uma pagina? então não deveria ser `page-authors-create`?

2021-05-17 17:41 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +  <div class="authors-create">
sim, mudado

2021-05-21 17:54 UTC, eliasassuncao requested changes

2021-05-21 17:54 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +    link: '/create-authors'
era melhor ser pelo name e não pelo path

2021-05-21 17:54 UTC, eliasassuncao commented on src/pages/authors/authorsCreate.vue
> +    <h1 class="page-authors-create__title text-h5 row justify-center q-py-md"> Criação de Autores </h1>
precisa dos espaços ?

2021-05-21 17:54 UTC, eliasassuncao commented on src/pages/authors/authorsCreate.vue
> +      email: null
é melhor string vazia

2021-05-21 17:54 UTC, eliasassuncao commented on src/pages/authors/authorsCreate.vue
> +      name: null,
é melhor string vazia

2021-05-21 17:54 UTC, eliasassuncao commented on src/pages/authors/authorsCreate.vue
> +    color: $primary;
não precisa dessa classe, existe uma classe do quasar `text-primary`

2021-05-21 18:25 UTC, cassioalmeida2 commented on src/layouts/MainLayout.vue
> +    link: '/create-authors'
utilizar o nome da página para ir seria melhor aqui

2021-05-21 18:25 UTC, cassioalmeida2 commented on src/pages/authors/authorsCreate.vue
> +      name: null,
por causa do name ser uma string no seu estado normal é melhor utilizar ele como string sem conteúdo no seu estado inicial: name: ''

2021-05-24 12:23 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +    <h1 class="page-authors-create__title text-h5 row justify-center q-py-md"> Criação de Autores </h1>
não

2021-05-24 12:24 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +      email: null
feito

2021-05-24 12:24 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +      name: null,
feito

2021-05-24 12:26 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +    color: $primary;
feito

2021-05-24 12:27 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +      name: null,
feito

2021-05-24 21:49 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +    link: '/create-authors'
feito

2021-05-24 21:49 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +    link: '/create-authors'
feito

2021-05-24 21:54 UTC, eliasassuncao requested changes

2021-05-24 21:54 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +                <essential-link v-for="name in essentialLinks" :key="name.title" :content="name" />
seria melhor `route`, não faz muito sentido `name.title`

2021-05-24 21:54 UTC, eliasassuncao commented on src/components/EssentialLink.vue
> +  <q-item :to="{name: content.name}">
faltou espaçamento entre as chaves

2021-05-25 00:39 UTC, felipejuzo02 commented on db.json
> +      "categoryOptions": [
faz sentido passar as opções de categorias para o json? n é melhor passar somente a selecionada?

2021-05-25 13:53 UTC, cassioalmeida2 commented on src/pages/authors/authorsCreate.vue
> +    <div class="row justify-center col col-md-8 q-pt-sm">
precisa do col ? somente o col-md-8 já não faria o que você precisa nesse caso?

2021-05-25 20:31 UTC, juliadelisposte commented on db.json
> +      "categoryOptions": [
Foi feito um alinhamento com o Cássio e com o Elias e retiramos o categoryOptions

2021-05-25 20:31 UTC, juliadelisposte commented on src/pages/authors/authorsCreate.vue
> +    <div class="row justify-center col col-md-8 q-pt-sm">
não precisa, o col-md-8 atendeu

2021-05-25 20:31 UTC, juliadelisposte commented on src/components/EssentialLink.vue
> +  <q-item :to="{name: content.name}">
feito

2021-05-25 20:32 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +                <essential-link v-for="name in essentialLinks" :key="name.title" :content="name" />
feito

2021-05-27 18:04 UTC, cassioalmeida2 approved these changes

2021-05-27 18:04 UTC, felipejuzo02 approved these changes

2021-05-27 18:07 UTC, eliasassuncao requested changes

2021-05-27 18:07 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +    name: 'PostsList'
poderia especificar melhor o que é, é um nome da rota, então poderia ser `routeName`

2021-05-28 16:22 UTC, juliadelisposte commented on src/layouts/MainLayout.vue
> +    name: 'PostsList'
feito

2021-05-28 16:56 UTC, eliasassuncao approved these changes

2021-05-28 17:06 UTC, merged